In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("pune.csv")

In [3]:
df

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location,solar_irradiance(W/m^2),power_generated(Watts)
0,11-12-2008 00:00,30,18,0,11.0,6,93,4:33 PM,5:13 AM,6:57 AM,...,72,0.0,1013,18,10,114,5,pune,517.50,93150
1,11-12-2008 01:00,30,18,0,11.0,6,93,4:33 PM,5:13 AM,6:57 AM,...,72,0.0,1013,19,10,125,4,pune,525.00,94500
2,11-12-2008 02:00,30,18,0,11.0,6,93,4:33 PM,5:13 AM,6:57 AM,...,72,0.0,1013,18,10,136,4,pune,532.50,95850
3,11-12-2008 03:00,30,18,0,11.0,6,93,4:33 PM,5:13 AM,6:57 AM,...,72,0.0,1013,18,10,147,4,pune,532.50,95850
4,11-12-2008 04:00,30,18,0,11.0,6,93,4:33 PM,5:13 AM,6:57 AM,...,68,0.0,1014,20,10,136,4,pune,577.50,103950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116131,11-03-2022 19:00,35,23,0,11.8,7,56,12:40 PM,1:33 AM,6:46 AM,...,28,0.0,1009,30,10,235,7,pune,822.50,148050
116132,11-03-2022 20:00,35,23,0,11.8,7,56,12:40 PM,1:33 AM,6:46 AM,...,29,0.0,1010,29,10,289,9,pune,813.75,146475
116133,11-03-2022 21:00,35,23,0,11.8,7,56,12:40 PM,1:33 AM,6:46 AM,...,30,0.0,1012,27,10,343,12,pune,796.25,143325
116134,11-03-2022 22:00,35,23,0,11.8,7,56,12:40 PM,1:33 AM,6:46 AM,...,31,0.0,1011,26,10,234,11,pune,805.00,144900
116135,11-03-2022 23:00,35,23,0,11.8,7,56,12:40 PM,1:33 AM,6:46 AM,...,32,0.0,1011,25,10,125,10,pune,813.75,146475

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116136 entries, 0 to 116135
Data columns (total 27 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   date_time                116136 non-null  object
 1   maxtempC                 116136 non-null  int64
 2   mintempC                 116136 non-null  int64
 3   totalSnow_cm             116136 non-null  int64
 4   sunHour                  116136 non-null  float64
 5   uvIndex                  116136 non-null  int64
 6   moon_illumination        116136 non-null  int64
 7   moonrise                 116136 non-null  object
 8   moonset                  116136 non-null  object
 9   sunrise                  116136 non-null  object
 10  sunset                   116136 non-null  object
 11  DewPointC                116136 non-null  int64
 12  FeelsLikeC               116136 non-null  int64
 13  HeatIndexC               116136 non-null  int64
 14  WindChillC               116136 non-null  int64
 15  WindGustKmph             116136 non-null  int64
 16  cloudcover               116136 non-null  int64
 17  humidity                 116136 non-null  int64
 18  precipMM                 116136 non-null  float64
 19  pressure                 116136 non-null  int64
 20  tempC                    116136 non-null  int64
 21  visibility               116136 non-null  int64
 22  winddirDegree            116136 non-null  int64
 23  windspeedKmph            116136 non-null  int64
 24  location                 116136 non-null  object
 25  solar_irradiance(W/m^2)  116136 non-null  float64
 26  power_generated(Watts)   116136 non-null  int64
dtypes: float64(3), int64(18), object(6)
memory usage: 23.9+ MB

In [5]:
df.isnull().sum()

date_time                  0
maxtempC                   0
mintempC                   0
totalSnow_cm               0
sunHour                    0
uvIndex                    0
moon_illumination          0
moonrise                   0
moonset                    0
sunrise                    0
sunset                     0
DewPointC                  0
FeelsLikeC                 0
HeatIndexC                 0
WindChillC                 0
WindGustKmph               0
cloudcover                 0
humidity                   0
precipMM                   0
pressure                   0
tempC                      0
visibility                 0
winddirDegree              0
windspeedKmph              0
location                   0
solar_irradiance(W/m^2)    0
power_generated(Watts)     0
dtype: int64

In [6]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\sonu\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy in c:\users\sonu\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\sonu\anaconda3\lib\site-packages (from xgboost) (1.13.1)

In [7]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Load dataset
df = pd.read_csv("pune.csv", parse_dates=["date_time"])

In [8]:
# Feature Engineering
df["date_time"] = pd.to_datetime(df["date_time"], format="%d-%m-%Y %H:%M")
df["hour"] = df["date_time"].dt.hour
df["day"] = df["date_time"].dt.day
df["month"] = df["date_time"].dt.month
df["year"] = df["date_time"].dt.year

In [9]:
# Selecting features and target variable
features = [
    "maxtempC", "mintempC", "sunHour", "uvIndex", "DewPointC",
    "FeelsLikeC", "WindGustKmph", "cloudcover", "humidity", "precipMM",
    "pressure", "tempC", "visibility", "winddirDegree", "windspeedKmph",
    "solar_irradiance(W/m^2)", "hour", "day", "month"
]

target = "power_generated(Watts)"

In [19]:
# Splitting dataset
X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
# Train XGBoost Model
print("Training model...")
model = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)
model.fit(X_train, y_train)
print("Model trained.")

Training model...
Model trained.

In [23]:
# Predict
print("Making predictions...")
y_pred = model.predict(X_test)

Making predictions...

In [25]:
# Check shape of y_pred
print("Shape of y_pred:", y_pred.shape)
print("First few predictions:", y_pred[:5])

Shape of y_pred: (23228,)
First few predictions: [9.5253410e+00 1.7099705e+05 2.1373803e+04 1.1338299e+05 1.7459623e+05]

In [27]:

# Evaluate
print("Evaluating predictions...")
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"MAE: {mae}")
print(f"RMSE: {rmse}")

Evaluating predictions...
MAE: 23.868705828731393
RMSE: 58.7463065326013

In [29]:
from sklearn.metrics import r2_score

# Predict
y_pred = model.predict(X_test)

# Calculate R-squared
r2 = r2_score(y_test, y_pred)

print(f"R-squared: {r2}")

R-squared: 0.9999988649073133